### ISSUE TITLE
OwlGenerator(File rdfDataset) not working

### ISSUE THREAD

**Issue by olivier-derom** [oeg-upm/astrea#13]
When using the OwlGenerator(File rdfDataset) variant of OwlGenerator, an error occurs because 'queries' is Null.
I believe this this because queries is not properly initialized yet.
This can be solved by adding the line `queries = new ArrayList<>();` within the function (on line 101 of OwlGenerator.java), similarly to how it happens in `OwlGenerator()` and `OwlGenerator(String endpoint)` 
This solved the problem for me.

**Comment by AndreaCimminoArriaga** [comment]
The variable is initialized in the constructor in the current code. In any case, could you create a PR proposing this change? Many thanks for contributing :)
