### ISSUE TITLE
fromURLs gives no output when 1+ wrong URL

### ISSUE THREAD

**Issue by olivier-derom** [oeg-upm/astrea#15]
When using the `fromURLs` method to generate shapes, where you give a list of URLs, rather than 1 by 1, if any of the URLs does not contain a valid ontology, an error occurs.
This prevents the creation of any SHACL file, not even from the other valid URLs in the list.
You could add a Try/Catch to still parse the valid URLs and generate a SHACL file from the valid URLs only, skipping the non-valid ones, but notifying the user. In this way, you at least have some output, rather than nothing.
I believe the API already does this somehow, (handled by code 206), but it would be nice to implement this in this code too.
I made these small changes and will create a pull request if you are interested in implementing this little fool-proofing enhancement.

**Comment by AndreaCimminoArriaga** [comment]
Yes, this was a feature it should be there maybe we thought about it and miss the implementation in the code. Thanks for contributing we definitely are merging the PR.
