### ISSUE TITLE
Astrea-KG.ttl not up to date?

### ISSUE THREAD

**Issue by olivier-derom** [oeg-upm/astrea#17]
When using the `OwlGenerator` with the latest `Astrea-KG.ttl` file containing an RDF dataset with the Astrea queries, I get other shapes (less constraints) compared to when I use `OwlGenerator` without argument (and it gets the queries from your servers).
Could this be because the `Astrea-KG.ttl` on github is outdated compared to the one you use for the API and on the servers?
If so, would it be possible to update it to the latest version, or make this one available somehow?

**Comment by AndreaCimminoArriaga** [comment]
I guess it could be that the `.ttl` is outdated. The server from where Astrea reads the shapes is this [one](https://astrea.helio.linkeddata.es/). You can download the whole dataset from there, in any case I will update the file in the git as well with the name `Astrea-KG-latest.ttl`
