### ISSUE TITLE
Online Java Documentation not available

### ISSUE THREAD

**Issue by olivier-derom** [oeg-upm/astrea#18]
In the ReadMe, at the bottom there is a link to the documentation [https://oeg-upm.github.io/Astrea/](https://oeg-upm.github.io/Astrea/), but it seems that link is broken, has the link maybe changed?

**Comment by AndreaCimminoArriaga** [comment]
This one is easy, try with the link all in lowercase https://oeg-upm.github.io/astrea/. This is odd because in theory links are case sensitive but git seems to care about it.
