### ISSUE TITLE
https://astrea.helio.linkeddata.es is unavailable

### ISSUE THREAD

**Issue by michaelp103103** [oeg-upm/Astrea#22]
We keep getting HTTP status code 503: Service Unavailable when trying to access https://astrea.helio.linkeddata.es

Also, when trying to follow the link to the java doc in the README, we get a "page not found" error.

**Comment by AndreaCimminoArriaga** [comment]
Dear Michael, we are having some troubles with the services. We hope machines will be ready and up soon, sorry for the inconveniences.
